### ISSUE TITLE
FloatingAction stays on screen if I change current fragment

### ISSUE THREAD

**Issue by pbouliou** [telly/FloatingAction#1]
Hello,

I added floatingaction to a fragment containing a listview. If I change the fragment using Navigation Drawer the floatingaction button stays on screen.
seen on 0.0.4

**Comment by eveliotc** [comment]
Please make sure to call `onDestroy` once you no longer need a `FloatingAction` instance, if you are using it within a `Fragment` you can call it from `onDestroyView`

**Comment by pbouliou** [comment]
Exact! thanks!
