### ISSUE TITLE
Can't resolve gradle dependency

### ISSUE THREAD

**Issue by StephaneBg** [telly/FloatingAction#2]
I added floating action to mu build.gradle but the library is not found.

dependencies {
    compile 'com.telly:floatingaction:0.0.4'
}

I get:
Error:Failed to find: com.telly:floatingaction:0.0.4

**Comment by pbouliou** [comment]
It seems that there was a bug in the tool used to deploy this lib on maven.
You can either wait that the author redeplay, or you can download the lib and add it manually to your project.

**Comment by eveliotc** [comment]
I've pushed it once more today, this time [it did actually make it to central](https://search.maven.org/remotecontent?filepath=com/telly/floatingaction/0.0.4/floatingaction-0.0.4.pom) please reopen this issue if your build script is still unable to resolve it.
